spring.application.name=techstore

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/techstore_db
spring.datasource.username=root
spring.datasource.password=123456

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# DATA INITIALIZATION 
# ===============================
spring.sql.init.mode=never

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# JWT
# ===============================
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970